//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCompositionDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Players()
        {
            this.Appearances = new HashSet<Appearances>();
            this.InstumentPerPlayers = new HashSet<InstumentPerPlayer>();
            this.PlayersInAppearances = new HashSet<PlayersInAppearances>();
        }
    
        public int codeP { get; set; }
        public Nullable<int> idP { get; set; }
        public string fullNameP { get; set; }
        public string pel { get; set; }
        public string email { get; set; }
        public int codePlays { get; set; }
        public Nullable<int> price { get; set; }
        public string daysWork { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appearances> Appearances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstumentPerPlayer> InstumentPerPlayers { get; set; }
        public virtual Places Place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayersInAppearances> PlayersInAppearances { get; set; }
    }
}
