//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instruments()
        {
            this.InstrumInCompositions = new HashSet<InstrumInCompositions>();
            this.InstumentPerPlayer = new HashSet<InstumentPerPlayer>();
            this.PlayersInAppearances = new HashSet<PlayersInAppearances>();
        }
    
        public int codeInst { get; set; }
        public string nameInst { get; set; }
        public int style { get; set; }
        public int size { get; set; }
        public int voice { get; set; }
        public int type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstrumInCompositions> InstrumInCompositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstumentPerPlayer> InstumentPerPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayersInAppearances> PlayersInAppearances { get; set; }
    }
}
