//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumInCompositions
    {
        public int codeIInComp { get; set; }
        public int codeInst { get; set; }
        public int codeComp { get; set; }
    
        public virtual Compositions Compositions { get; set; }
        public virtual Instruments Instruments { get; set; }
    }
}
