//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class musicCompositionEntities : DbContext
    {
        public musicCompositionEntities()
            : base("name=musicCompositionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public DbSet<T> GetDbSet<T>() where T : class
        {
            return this.Set<T>();
        }
        public virtual DbSet<Appearances> Appearances { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Compositions> Compositions { get; set; }
        public virtual DbSet<Instruments> Instruments { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<PlayersInAppearances> PlayersInAppearances { get; set; }
        public virtual DbSet<InstrumInCompositions> InstrumInCompositions { get; set; }
        public virtual DbSet<InstumentPerPlayer> InstumentPerPlayer { get; set; }
    }
}
