//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayersInAppearances
    {
        public int codePInA { get; set; }
        public int codeA { get; set; }
        public int codeP { get; set; }
        public int codeInst { get; set; }
    
        public virtual Appearances Appearances { get; set; }
        public virtual Players Players { get; set; }
        public virtual Instruments Instruments { get; set; }
    }
}
